name: Build on Pull Request closed
on:    
  pull_request:
  types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    needs: [test]
    - name: Get Repository
      uses: actions/checkout@v3
    - name: Setup Docker qemu
      uses: docker.setup-qemu-action@v1
    - name: Setup Docker buildX
      uses: docker/setup-buildx-action@v1
    - name: login Dockerhub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push docker
      uses: docker/build-push-action@v2
      with:
        push: true
        tag: ${{ secrets.DOCKER_USERNAME }}/wether:latest
