name: DockerBuild

on: 
  pull_request:
    branches:
      - master
    types:
      - closed
env:
  APP_VERSION: 1.0.0

jobs:
  Build-App:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/setup-qemu-action@v1
      - name: Installation docker BuildX
        uses: docker/setup-buildx-action@v1
      - name:  Login & password docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME_DOCKER}}
          password: ${{secrets.PASSWORD_DOCKER}}
      - name: build & push 
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.USERNAME_DOCKER}}/pyapp:${{env.APP_VERSION}}

      

