# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  repository_dispatch:
      types: [run-testrail-report]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]


    env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        TESTRAIL_REPORT_TYPE:  ${{ github.event.client_payload.kind }}
        
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
      - run: 'echo TESTRAIL_REPORT_TYPE'
      - run: |
            echo (python testrail_utils.py $TESTRAIL_REPORT_TYPE) >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: for_test
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket: '
          SLACK_TITLE: Post Title
          SLACK_USERNAME: testrail
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

